INSERT INTO Telepules (orszag, megye, telepules) VALUES ('Magyarország', 'Békés', 'Mezőkovácsháza');
INSERT INTO Telepules (orszag, megye, telepules) VALUES ('Magyarország', 'Békés', 'Gyula');
INSERT INTO Telepules (orszag, megye, telepules) VALUES ('Magyarország', 'Pest', 'Budapest');
INSERT INTO Telepules (orszag, megye, telepules) VALUES ('Magyarország', 'Borsod-Abaúj-Zemplén', 'Miskolc');
INSERT INTO Telepules (orszag, megye, telepules) VALUES ('Magyarország', 'Győr-Moson-Sopron', 'Győr');
INSERT INTO Telepules (orszag, megye, telepules) VALUES ('Magyarország', 'Csongrád-Csanád', 'Szeged');
INSERT INTO Telepules (orszag, megye, telepules) VALUES ('Magyarország', 'Hajdú-Bihar', 'Debrecen');
INSERT INTO Telepules (orszag, megye, telepules) VALUES ('Magyarország', 'Békés', 'Békéscsaba');
INSERT INTO Kategoria (nev) VALUES ('Kertészet');
INSERT INTO Kategoria (nev) VALUES ('Naplemente');
INSERT INTO Kategoria (nev) VALUES ('Sikeresen módosítva');
INSERT INTO Kategoria (nev) VALUES ('Természet');
INSERT INTO Kategoria (nev) VALUES ('Túrázás');
INSERT INTO Kategoria (nev) VALUES ('Utackép');
INSERT INTO Kategoria (nev) VALUES ('Valóságsó');
INSERT INTO Kategoria (nev) VALUES ('Városkép');
INSERT INTO Kategoria (nev) VALUES ('ez is egy teszt');
INSERT INTO Kategoria (nev) VALUES ('Évszakok');
INSERT INTO Felhasznalo (felhasznalonev, vezeteknev, keresztnev, admin, email, jelszo, telepules_id) VALUES ('tesztelek2', 'Nem', 'Tesztelek', 1, 'tesztelek2@pelda.hu', '$2y$10$NQQbGai/Db7wor17E8jwQOZK5IZtgsiWz/F8SdFYByULep2xEGmwm', 4);
INSERT INTO Felhasznalo (felhasznalonev, vezeteknev, keresztnev, admin, email, jelszo, telepules_id) VALUES ('Nyivaak', 'Mekk', 'Elek', 0, 'ansela828@gmail.com', '$2y$12$CqV8bDguJQh6/DkuilOfeuhFulhCzo1APoG.DV3v00BPfLEEk57IO', 2);
INSERT INTO Felhasznalo (felhasznalonev, vezeteknev, keresztnev, admin, email, jelszo, telepules_id) VALUES ('user1', 'Kovács', 'Péter', 0, 'user1@pelda.hu', 'pw1', 1);
INSERT INTO Felhasznalo (felhasznalonev, vezeteknev, keresztnev, admin, email, jelszo, telepules_id) VALUES ('user2', 'Nagy', 'Anna', 1, 'user2@pelda.hu', 'pw2', 2);
INSERT INTO Felhasznalo (felhasznalonev, vezeteknev, keresztnev, admin, email, jelszo, telepules_id) VALUES ('user3', 'Szabó', 'László', 0, 'user3@pelda.hu', 'pw3', 3);
INSERT INTO Felhasznalo (felhasznalonev, vezeteknev, keresztnev, admin, email, jelszo, telepules_id) VALUES ('user4', 'Tóth', 'Júlia', 0, 'user4@pelda.hu', 'pw4', 4);
INSERT INTO Felhasznalo (felhasznalonev, vezeteknev, keresztnev, admin, email, jelszo, telepules_id) VALUES ('user5', 'Horváth', 'Béla', 0, 'user5@pelda.hu', 'pw5', 5);
INSERT INTO Felhasznalo (felhasznalonev, vezeteknev, keresztnev, admin, email, jelszo, telepules_id) VALUES ('tesztelek3', 'Igen', 'Tesztelek', 0, 'tesztelek3@teszt.hu', '$2y$10$ywhh3EiCXZqzlO1d6PfWW.q72Sg5tslN09fVax1eegY7SzGMg.qYa', 1);
INSERT INTO Felhasznalo (felhasznalonev, vezeteknev, keresztnev, admin, email, jelszo, telepules_id) VALUES ('Alma', 'Alma', 'Fa', 0, 'alma@gmail.com', '$2y$12$hJ82u00J9f7bXuZP0PIv7eXu8rGzHbfLMAR0WZqWer28JPKIkyaYG', 4);
INSERT INTO Felhasznalo (felhasznalonev, vezeteknev, keresztnev, admin, email, jelszo, telepules_id) VALUES ('kukacandor', 'Kukac', 'Andor', 0, 'kukacandor@gmail.com', '$2y$12$u4z3zSnLZNtwXa8YTwPydORnpg6zs0JgTv9lTaoXwaScJkibQcG0i', 1);
INSERT INTO Felhasznalo (felhasznalonev, vezeteknev, keresztnev, admin, email, jelszo, telepules_id) VALUES ('kelemen2009', 'Hajdú', 'Kelemen', 0, 'nagyonjo@kelemen.hu', '$2y$12$jQlsNi0zbDWB6eFl/b4oneA/sFj8a7QlKSD/Cc7Iz0MFtMsFMsmZK', 5);
INSERT INTO Felhasznalo (felhasznalonev, vezeteknev, keresztnev, admin, email, jelszo, telepules_id) VALUES ('kortepeter', 'Körte', 'Péter', 0, 'kortepeter@gmail.hu', 'kortepeter123', 5);
INSERT INTO Felhasznalo (felhasznalonev, vezeteknev, keresztnev, admin, email, jelszo, telepules_id) VALUES ('tesztelek', 'Teszt', 'Elek', 1, 'tesztelek@pelda.hu', '$2y$10$JuO5Zx8qVCsT/22aAP.BY.9t0Z/d5rbqncQw6sp3tMW.cNwpVZ2yK', 6);
INSERT INTO Felhasznalo (felhasznalonev, vezeteknev, keresztnev, admin, email, jelszo, telepules_id) VALUES ('trabantal', 'Trab', 'Antal', 0, 'trabantal@gmail.com', '$2y$12$25Luzt7JaEWL.PhrjGN4ROy6iSVRKG1umqClB3leUnmEycRNTtVSu', 4);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-25 14:56:18', 'YYYY-MM-DD HH24:MI:SS'), 'sziacicus', empty_blob(), 'hehe én egy macska vagyok miau!', 'tesztelek', 2);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-05-07 22:20:43', 'YYYY-MM-DD HH24:MI:SS'), 'ENGEM IS', empty_blob(), 'TÖLTS FEL KÉRLEK', 'tesztelek2', 3);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-26 22:58:18', 'YYYY-MM-DD HH24:MI:SS'), 'asdasdas', empty_blob(), 'dasdas', 'tesztelek2', 1);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-05-15 14:20:02', 'YYYY-MM-DD HH24:MI:SS'), 'ocsemrol is kep', empty_blob(), 'o is jol nez ki', 'kukacandor', 6);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-25 14:23:16', 'YYYY-MM-DD HH24:MI:SS'), 'Utackép', empty_blob(), 'Nagyon szép utca.', 'tesztelek', 6);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-25 14:27:02', 'YYYY-MM-DD HH24:MI:SS'), 'Teszt', empty_blob(), 'teszt.', 'tesztelek', 1);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-25 14:37:07', 'YYYY-MM-DD HH24:MI:SS'), 'Teszt', empty_blob(), 'teszt.', 'tesztelek', 6);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-26 16:57:07', 'YYYY-MM-DD HH24:MI:SS'), 'VALAMI KÉEP', empty_blob(), 'FXDYFYDXFYXDFYDX', 'tesztelek2', 2);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-05-15 14:08:29', 'YYYY-MM-DD HH24:MI:SS'), 'wert', empty_blob(), 'wert', 'trabantal', 2);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-05-15 14:09:17', 'YYYY-MM-DD HH24:MI:SS'), 'r6u', empty_blob(), 'ertuy', 'trabantal', 5);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-05-15 14:17:29', 'YYYY-MM-DD HH24:MI:SS'), 'Uj kep magamrol', empty_blob(), 'jok voltak a fenyviszonyok', 'kukacandor', 5);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-25 14:40:16', 'YYYY-MM-DD HH24:MI:SS'), 'FASDFSADF', empty_blob(), 'FASDFASDFSADF', 'tesztelek', 5);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-05-07 14:33:46', 'YYYY-MM-DD HH24:MI:SS'), 'ÚJJJJ', empty_blob(), 'DSAFDSAF', 'tesztelek', 6);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-05-15 14:07:14', 'YYYY-MM-DD HH24:MI:SS'), 'valami', empty_blob(), 'ihgfoiug', 'trabantal', 5);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-05-15 14:20:41', 'YYYY-MM-DD HH24:MI:SS'), 'god', empty_blob(), ':pray:', 'kukacandor', 1);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-05-15 14:55:32', 'YYYY-MM-DD HH24:MI:SS'), 'bbc', empty_blob(), '', 'kelemen2009', 5);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-05-15 15:34:30', 'YYYY-MM-DD HH24:MI:SS'), 'szevasztok', empty_blob(), '', 'kelemen2009', 5);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-24 17:00:24', 'YYYY-MM-DD HH24:MI:SS'), 'Naplemente', empty_blob(), 'Nagyon szép naplemente.', 'user1', 1);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-24 17:00:24', 'YYYY-MM-DD HH24:MI:SS'), 'Téli táj', empty_blob(), 'Nagyon szép havas erdő télen.', 'user2', 2);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-24 17:00:24', 'YYYY-MM-DD HH24:MI:SS'), 'Városi éjszaka', empty_blob(), 'Nagyon-nagyon szép éjszakai fények.', 'user3', 3);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-24 17:00:24', 'YYYY-MM-DD HH24:MI:SS'), 'Tavaszi rét', empty_blob(), 'Nagyon szép tavasz.', 'user4', 4);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-24 17:00:24', 'YYYY-MM-DD HH24:MI:SS'), 'Hegyi túra', empty_blob(), 'Kilátás.', 'user5', 5);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-05-15 14:05:59', 'YYYY-MM-DD HH24:MI:SS'), 'asd', empty_blob(), 'asd', 'trabantal', 4);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-25 14:51:05', 'YYYY-MM-DD HH24:MI:SS'), 'Orbán vagyok', empty_blob(), 'Orbán egy geci xddddd', 'tesztelek', 6);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-25 16:17:50', 'YYYY-MM-DD HH24:MI:SS'), 'Legújabb kép kategóriával együtt.', empty_blob(), 'Ez a kép tartalmaz valamilyen kategóriát.', 'tesztelek', 1);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-25 16:22:31', 'YYYY-MM-DD HH24:MI:SS'), 'Ez a kép nem tartalmaz kategóriát.', empty_blob(), 'NOOOOOOOOOOOOO KATEGORRRYY', 'tesztelek', 1);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-26 17:00:06', 'YYYY-MM-DD HH24:MI:SS'), 'Sok szöveg', empty_blob(), 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum', 'tesztelek2', 1);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-05-15 14:11:08', 'YYYY-MM-DD HH24:MI:SS'), 'random hs screenshot #1', empty_blob(), 'random hs screenshot #1', 'trabantal', 5);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-05-15 14:43:20', 'YYYY-MM-DD HH24:MI:SS'), 'digikep', empty_blob(), 'Nem egy jó élmény..', 'tesztelek', 4);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-05-07 14:33:27', 'YYYY-MM-DD HH24:MI:SS'), 'NFADSFDSA', empty_blob(), 'FDSAFDSA', 'tesztelek', 6);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-04-26 22:58:47', 'YYYY-MM-DD HH24:MI:SS'), 'aAAAAAAAAAAAAAAAA', empty_blob(), 'AAAAAAAAAAAAAAAAAAAAAAAAA', 'tesztelek2', 7);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-05-07 17:42:36', 'YYYY-MM-DD HH24:MI:SS'), 'Am', empty_blob(), 'Luk', 'Alma', 5);
INSERT INTO Kep (feltoltesi_datum, cim, kep_binaris, leiras, felhasznalo_felhasznalonev, telepules_id) VALUES (TO_TIMESTAMP('2025-05-07 22:05:46', 'YYYY-MM-DD HH24:MI:SS'), 'Cicák', empty_blob(), 'Szeretik egymást', 'Nyivaak', 6);
INSERT INTO Fenykepalbum (nev, leiras, letrehozasi_datum, felhasznalo_felhasznalonev) VALUES ('Természeti furcsaállatok XD', 'Természeti furcsaállatok.', TO_TIMESTAMP('2025-04-26 21:23:30', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek');
INSERT INTO Fenykepalbum (nev, leiras, letrehozasi_datum, felhasznalo_felhasznalonev) VALUES ('ALBUM OLDALRÓL', 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.', TO_TIMESTAMP('2025-04-26 17:20:22', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek2');
INSERT INTO Fenykepalbum (nev, leiras, letrehozasi_datum, felhasznalo_felhasznalonev) VALUES ('Állatkert', 'Ez egy vicces hely. xd ', TO_TIMESTAMP('2025-04-26 21:23:46', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek');
INSERT INTO Fenykepalbum (nev, leiras, letrehozasi_datum, felhasznalo_felhasznalonev) VALUES ('Amit nem kellett volna feltoltenem', 'en butus elfelejtettem hogyan kell torolni', TO_TIMESTAMP('2025-05-15 14:10:21', 'YYYY-MM-DD HH24:MI:SS'), 'trabantal');
INSERT INTO Fenykepalbum (nev, leiras, letrehozasi_datum, felhasznalo_felhasznalonev) VALUES ('Duranda', 'asd', TO_TIMESTAMP('2025-05-15 14:56:49', 'YYYY-MM-DD HH24:MI:SS'), 'kelemen2009');
INSERT INTO Fenykepalbum (nev, leiras, letrehozasi_datum, felhasznalo_felhasznalonev) VALUES ('ez pez', 'heheheha', TO_TIMESTAMP('2025-05-15 14:20:58', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor');
INSERT INTO Fenykepalbum (nev, leiras, letrehozasi_datum, felhasznalo_felhasznalonev) VALUES ('Természet képek', 'Gyönyörű természetfotók.', TO_TIMESTAMP('2025-04-24 17:00:24', 'YYYY-MM-DD HH24:MI:SS'), 'user1');
INSERT INTO Fenykepalbum (nev, leiras, letrehozasi_datum, felhasznalo_felhasznalonev) VALUES ('Városi élet', 'Parádés éjszakai és nappali városképek.', TO_TIMESTAMP('2025-04-24 17:00:24', 'YYYY-MM-DD HH24:MI:SS'), 'user2');
INSERT INTO Fenykepalbum (nev, leiras, letrehozasi_datum, felhasznalo_felhasznalonev) VALUES ('Évszakok', 'Képek az évszakokról.', TO_TIMESTAMP('2025-04-24 17:00:24', 'YYYY-MM-DD HH24:MI:SS'), 'user3');
INSERT INTO Fenykepalbum (nev, leiras, letrehozasi_datum, felhasznalo_felhasznalonev) VALUES ('Túrázók albuma', 'Legkomolyabb túrázós fotók.', TO_TIMESTAMP('2025-04-24 17:00:24', 'YYYY-MM-DD HH24:MI:SS'), 'user4');
INSERT INTO Fenykepalbum (nev, leiras, letrehozasi_datum, felhasznalo_felhasznalonev) VALUES ('Naplementék', 'Gyönyörű naplementék.', TO_TIMESTAMP('2025-04-24 17:00:24', 'YYYY-MM-DD HH24:MI:SS'), 'user5');
INSERT INTO Fenykepalbum (nev, leiras, letrehozasi_datum, felhasznalo_felhasznalonev) VALUES ('ASDASSSASD', 'ASFASFASFAS', TO_TIMESTAMP('2025-04-27 10:43:58', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek');
INSERT INTO Fenykepalbum (nev, leiras, letrehozasi_datum, felhasznalo_felhasznalonev) VALUES ('HHHHHHHHHHHH', 'HHHHHHHHHHHHHHHHHHH', TO_TIMESTAMP('2025-04-27 10:44:25', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (1, 'Naplemente');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (2, 'Évszakok');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (3, 'Városkép');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (4, 'Természet');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (5, 'Túrázás');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (6, 'Utackép');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (7, 'Naplemente');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (9, 'Túrázás');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (24, 'Túrázás');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (11, 'Városkép');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (12, 'Természet');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (13, 'Naplemente');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (13, 'Természet');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (13, 'Túrázás');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (23, 'Naplemente');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (23, 'Túrázás');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (23, 'Évszakok');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (24, 'Kertészet');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (26, 'Kertészet');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (27, 'Túrázás');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (32, 'Kertészet');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (11, 'Naplemente');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (32, 'Sikeresen módosítva');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (11, 'Természet');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (32, 'Túrázás');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (22, 'Utackép');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (32, 'Valóságsó');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (32, 'Városkép');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (32, 'ez is egy teszt');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (32, 'Évszakok');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (31, 'Természet');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (24, 'Évszakok');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (24, 'Utackép');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (24, 'Valóságsó');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (24, 'Naplemente');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (22, 'Valóságsó');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (22, 'ez is egy teszt');
INSERT INTO KepKategoria (kep_id, kategoria_nev) VALUES (22, 'Sikeresen módosítva');
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (24, 11, 1);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (11, 2, 1);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (9, 3, 1);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (7, 4, 2);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (11, 5, 3);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (11, 6, 4);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (22, 7, 1);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (13, 8, 2);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (11, 9, 1);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (15, 11, 1);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (22, 12, 2);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (32, 13, 3);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (11, 11, 1);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (2, 3, 2);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (3, 2, 3);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (4, 1, 4);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (5, 4, 5);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (10, 2, 2);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (13, 3, 3);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (14, 4, 4);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (6, 6, 5);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (7, 8, 6);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (9, 2, 7);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (12, 2, 8);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (11, 1, 1);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (10, 1, 2);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (9, 1, 3);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (14, 2, 1);
INSERT INTO KepFenykepalbum (kep_id, fenykepalbum_id, sorszam) VALUES (13, 5, 2);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('tesztelek', 1, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('tesztelek', 7, 1);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 2, 1);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 3, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 9, 3);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 4, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 24, 1);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 6, 4);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kelemen2009', 13, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kelemen2009', 5, 3);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kelemen2009', 6, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kelemen2009', 7, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kelemen2009', 8, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kelemen2009', 9, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('tesztelek', 10, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('tesztelek', 27, 3);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 11, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 12, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 13, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 14, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 15, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 16, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 17, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 18, 3);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kelemen2009', 27, 3);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kelemen2009', 11, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('Alma', 19, 3);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 20, 2);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 21, 4);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 22, 4);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kelemen2009', 23, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kelemen2009', 24, 4);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kelemen2009', 25, 3);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('user1', 2, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('user2', 3, 4);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('user3', 4, 3);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('user4', 5, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('user5', 1, 4);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('tesztelek', 14, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('tesztelek', 23, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('tesztelek', 26, 5);
INSERT INTO Ertekeles (felhasznalo_felhasznalonev, kep_id, pontszam) VALUES ('kukacandor', 27, 4);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('nem. (4)', TO_TIMESTAMP('2025-04-26 13:12:38', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek2', 14, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Ne válaszolj rám.', TO_TIMESTAMP('2025-04-26 14:28:55', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek', 13, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('fuj ezt tenyleg nem kellett volna, undorito! torold le', TO_TIMESTAMP('2025-05-15 14:18:30', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 11, 1);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Már késő.', TO_TIMESTAMP('2025-04-26 14:29:02', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek', 13, 2);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Igen ez TÉNYLEG egy HOSSZÚ SZÖVEG', TO_TIMESTAMP('2025-04-26 15:25:25', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek2', 24, 2);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Burjánzik az idő (1)', TO_TIMESTAMP('2025-04-26 13:09:14', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek2', 14, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Én is hozzá akarok szólni.', TO_TIMESTAMP('2025-04-26 15:25:39', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek2', 24, 3);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('XD', TO_TIMESTAMP('2025-04-26 17:39:12', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek', 14, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('ez mi nem ertek kinaiul', TO_TIMESTAMP('2025-05-15 14:18:53', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 11, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('jo ido lesz', TO_TIMESTAMP('2025-05-15 14:19:17', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 9, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('global elite vagyok szarok', TO_TIMESTAMP('2025-05-15 14:22:28', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 12, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('elado a noveny', TO_TIMESTAMP('2025-05-15 14:29:11', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 13, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('like', TO_TIMESTAMP('2025-05-15 15:35:15', 'YYYY-MM-DD HH24:MI:SS'), 'kelemen2009', 14, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('asdferhtw', TO_TIMESTAMP('2025-05-15 15:22:24', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 15, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('barack', TO_TIMESTAMP('2025-05-15 15:22:29', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 16, 4);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Szerintem én hülye vagyok xd', TO_TIMESTAMP('2025-04-26 14:27:38', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek', 10, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Előfordulhat', TO_TIMESTAMP('2025-04-26 14:27:48', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek', 10, 5);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Hol jelenek meg ha írok?', TO_TIMESTAMP('2025-04-26 14:28:02', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek', 10, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Ez tényleg hosszú szöveg.', TO_TIMESTAMP('2025-04-26 15:24:54', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek2', 24, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('asfasdfa', TO_TIMESTAMP('2025-05-04 15:40:53', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek', 27, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('same', TO_TIMESTAMP('2025-05-15 14:12:06', 'YYYY-MM-DD HH24:MI:SS'), 'trabantal', 27, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('nem javitottak meg ki, de sztem max pontra megirtam a zht lesss goooooo', TO_TIMESTAMP('2025-05-15 15:21:00', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 13, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('bbc', TO_TIMESTAMP('2025-05-15 15:21:10', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 17, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('de csuuunyaaaa', TO_TIMESTAMP('2025-05-15 15:22:11', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 18, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('ez a trinyó', TO_TIMESTAMP('2025-05-15 15:22:34', 'YYYY-MM-DD HH24:MI:SS'), 'kelemen2009', 19, 6);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('majdnem elajultam', TO_TIMESTAMP('2025-05-15 15:22:37', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 20, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('en sem tudom', TO_TIMESTAMP('2025-05-15 15:22:54', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 21, 7);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('mi ez tesztelek', TO_TIMESTAMP('2025-05-15 15:23:02', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 22, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('tetszik a setup!!!', TO_TIMESTAMP('2025-05-15 15:23:07', 'YYYY-MM-DD HH24:MI:SS'), 'kelemen2009', 23, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('makcsa', TO_TIMESTAMP('2025-05-15 15:23:40', 'YYYY-MM-DD HH24:MI:SS'), 'kelemen2009', 27, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Fasza lett faszi', TO_TIMESTAMP('2025-05-07 17:43:04', 'YYYY-MM-DD HH24:MI:SS'), 'Alma', 24, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('ajjaj ezt lehet nem kellett volna feltoltenem!', TO_TIMESTAMP('2025-05-15 14:09:50', 'YYYY-MM-DD HH24:MI:SS'), 'trabantal', 25, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('dr miniszterelnok ur!', TO_TIMESTAMP('2025-05-15 14:21:30', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 26, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('en vagyok gunter schlierkamp', TO_TIMESTAMP('2025-05-15 14:23:18', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 23, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('az komoly', TO_TIMESTAMP('2025-05-15 15:26:19', 'YYYY-MM-DD HH24:MI:SS'), 'kelemen2009', 27, 3);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('örülök ha meglesz az 5.5', TO_TIMESTAMP('2025-05-15 15:26:38', 'YYYY-MM-DD HH24:MI:SS'), 'kelemen2009', 28, 8);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('trianon elott be like', TO_TIMESTAMP('2025-05-15 15:27:28', 'YYYY-MM-DD HH24:MI:SS'), 'kelemen2009', 10, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('nemtom', TO_TIMESTAMP('2025-05-15 15:27:55', 'YYYY-MM-DD HH24:MI:SS'), 'kelemen2009', 6, 9);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Nagyon komoly kép lett!', TO_TIMESTAMP('2025-04-24 17:00:24', 'YYYY-MM-DD HH24:MI:SS'), 'user2', 1, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Nagyon tetszik ez a fotó!', TO_TIMESTAMP('2025-04-24 17:00:24', 'YYYY-MM-DD HH24:MI:SS'), 'user3', 2, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Szuper helyszín!', TO_TIMESTAMP('2025-04-24 17:00:24', 'YYYY-MM-DD HH24:MI:SS'), 'user4', 3, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Szép, mint egy új traktor!', TO_TIMESTAMP('2025-04-24 17:00:24', 'YYYY-MM-DD HH24:MI:SS'), 'user5', 4, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Nem lett jó!', TO_TIMESTAMP('2025-04-24 17:00:24', 'YYYY-MM-DD HH24:MI:SS'), 'user1', 5, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Vlaami', TO_TIMESTAMP('2025-04-27 15:41:33', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek', 24, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Köszi baszomaszád', TO_TIMESTAMP('2025-05-07 17:43:14', 'YYYY-MM-DD HH24:MI:SS'), 'Alma', 11, 10);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Szeretlek bébéy', TO_TIMESTAMP('2025-05-07 22:06:30', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek', 12, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('AAAWWWOOOOOGAAA', TO_TIMESTAMP('2025-05-07 22:07:20', 'YYYY-MM-DD HH24:MI:SS'), 'Nyivaak', 13, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('AWAWAWAWAWA', TO_TIMESTAMP('2025-05-07 22:07:38', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek', 14, 11);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Elesett már a vár (2)', TO_TIMESTAMP('2025-04-26 13:09:26', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek2', 14, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Én egy különálló szöveg vagyok.', TO_TIMESTAMP('2025-04-26 15:25:52', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek2', 24, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('megvan mar vajon a 150 rekord', TO_TIMESTAMP('2025-05-15 14:29:47', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 6, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Én jobban��������', TO_TIMESTAMP('2025-05-07 22:08:04', 'YYYY-MM-DD HH24:MI:SS'), 'Nyivaak', 16, 12);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('mik ezek', TO_TIMESTAMP('2025-05-15 14:11:40', 'YYYY-MM-DD HH24:MI:SS'), 'trabantal', 15, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('me', TO_TIMESTAMP('2025-05-15 14:11:53', 'YYYY-MM-DD HH24:MI:SS'), 'trabantal', 17, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('egyetertek', TO_TIMESTAMP('2025-05-15 14:12:46', 'YYYY-MM-DD HH24:MI:SS'), 'trabantal', 11, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('jo kard', TO_TIMESTAMP('2025-05-15 14:25:09', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 18, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('nagyon deep', TO_TIMESTAMP('2025-05-15 15:24:16', 'YYYY-MM-DD HH24:MI:SS'), 'kelemen2009', 19, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('ez nagymagyarország?', TO_TIMESTAMP('2025-05-15 15:27:17', 'YYYY-MM-DD HH24:MI:SS'), 'kelemen2009', 10, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Vajon az idő megáll? (3)', TO_TIMESTAMP('2025-04-26 13:12:00', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek2', 14, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Végre működik az idő! (5)', TO_TIMESTAMP('2025-04-26 13:17:48', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek2', 14, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Én is itt vagyok!', TO_TIMESTAMP('2025-04-26 14:29:48', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek2', 13, 2);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('Törölhető vagyok.', TO_TIMESTAMP('2025-04-26 14:29:55', 'YYYY-MM-DD HH24:MI:SS'), 'tesztelek2', 13, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('omg', TO_TIMESTAMP('2025-05-15 14:12:15', 'YYYY-MM-DD HH24:MI:SS'), 'trabantal', 27, 13);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('macska nem tudja megnyomni a mouse button 1-et a kep feltoltesehez hazudsz', TO_TIMESTAMP('2025-05-15 14:23:52', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 12, NULL);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('az', TO_TIMESTAMP('2025-05-15 14:25:13', 'YYYY-MM-DD HH24:MI:SS'), 'kukacandor', 11, 14);
INSERT INTO Hozzaszolas (szoveg, datum, felhasznalo_felhasznalonev, kep_id, szulo_id) VALUES ('jön a savas eső romániából', TO_TIMESTAMP('2025-05-15 15:25:03', 'YYYY-MM-DD HH24:MI:SS'), 'kelemen2009', 7, NULL);


